CREATE TABLE IF NOT EXISTS public.financial_data (
    ID BIGINT NOT NULL,
    SYMBOL VARCHAR(10) NOT NULL,
    PRICE NUMERIC(10,2),
    VOLUME BIGINT,
    TRADE_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    METADATA_JSON JSONB,
    PRIMARY KEY (ID)
);

-- Source: PROD_DB.PUBLIC.FINANCIAL_DATA
-- Extracted: 2024-12-26 15:45:30
-- Rows: 1,250,000